### ISSUE TITLE
error con labels vacios

### ISSUE THREAD

**Issue by Z4mbr4** [xe-nvdk/ezcompose#10]
Cuando ejecutamos ezcompose e indicamos que no queremos labels lo agrega igual generando un error al momento de ejecutar el docker-compose up -d
![issue](https://user-images.githubusercontent.com/102488531/167986502-5bc490af-2bdd-4e03-9f9d-e848ffa44f37.png)

**Comment by xe-nvdk** [comment]
Buenas @Z4mbr4 gracias por reportar el error, lo reviso y libero una nueva version. Te aviso por acá también así lo probas.

**Comment by xe-nvdk** [comment]
Hola, acabo de probar y revisar el codigo, si le pones que no a los labels, no los agrega. Cierro el issue. Avísame cualquier cosa. Saludos.
